# -*- coding: utf-8 -*-
"""AudioCaptcha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_wTA_FBWIfkZWmE3TJm-kIV_OZOtFZq
"""



!pip install pyttsx3
!pip install pydub
!pip install gtts

import random
import string
from gtts import gTTS
from pydub import AudioSegment
from pydub.playback import play

def generate_random_captcha(length=6):
  characters = string.ascii_uppercase + string.digits
  captcha = ''.join(random.choices(characters, k = length))
  return captcha

def generate_audio_captcha(captcha_text, output_file = "audio_captcha.mp3"):
  tts = gTTS(captcha_text)
  tts.save(output_file)
  print(f"Audio CAPTCA saved as {output_file}")

def play_audio_captcha(audio_file):
  audio = AudioSegment.from_file(audio_file, format="mp3")
  play(audio)

if __name__ == "__main__":
  captcha_text = generate_random_captcha()
  print(f"Generated CAPTCHA : {captcha_text}")

  audio_file = "audio_captcha.mp3"
  generate_audio_captcha(captcha_text, audio_file)

  play_audio_captcha(audio_file)

